app = angular.module('ZSSN', []);
app.controller('SurvivorController', function($scope, $http) {
  
  //Select all the survivors from the server
  $http({
    method: "GET",
    url : "http://zssn-backend-example.herokuapp.com/api/people.json"

  }).then(function success(response){
      $scope.survivors = response.data;
      
  });

  //Register a new survivor 
  $scope.enviar = function(){

    //Organize elements to create the "Inventory" field
    var items = {
      Water: parseInt(angular.element('#water').val()),
      Food: parseInt(angular.element('#food').val()),
      Medication: parseInt(angular.element('#medication').val()),
      Ammunition: parseInt(angular.element('#ammunition').val())
    }

    //Organize latitude and longitude to create the parameter "lonlat" for location
    var lonlat = "POINT (" + $scope.lat + " " + $scope.long + ")";

    //Show on console the data, ready to be submitted
    console.log("name:" + $scope.name);
    console.log("age:" + $scope.age);
    console.log("gender:" + angular.element('#gender').val());
    console.log("lonlat:" + lonlat);
    console.log("items:" + JSON.stringify(items));
    
    //Union of parameters for post submit
    var params= {
      name: $scope.name,
      age: $scope.age,
      gender: angular.element('#gender').val(),
      lonlat: lonlat,
      items: items
    }
    //Method call to submit data
    $http.post("http://zssn-backend-example.herokuapp.com/api/people.json", params).success(function(data, status) {
            console.log(data);
        })
  }

  //Select the data related to quantity of infected survivors
  $http({
    method : "GET",
    url : "http://zssn-backend-example.herokuapp.com/api/report/infected.json"

  }).then(function mySucces(response) {
      $scope.infected = response.data;
    }, function myError(response) {
      $scope.infected = response.statusText;
  });

  //Select the data related to quantity of non-infected survivors
  $http({
  method : "GET",
  url : "http://zssn-backend-example.herokuapp.com/api/report/non_infected.json"

  }).then(function mySucces(response) {
      $scope.healthy = response.data;

    }, function myError(response) {
      $scope.healthy = response.statusText;
  });

  //Select the data related to survivors' inventories
  $http({
  method : "GET",
  url : "http://zssn-backend-example.herokuapp.com/api/report/people_inventory.json"

  }).then(function mySucces(response) {
      $scope.inventory = response.data;

    }, function myError(response) {
      $scope.inventory = response.statusText;
  });

  //Select the data related to infected points lost
  $http({
  method : "GET",
  url : "http://zssn-backend-example.herokuapp.com/api/report/infected_points.json"

  }).then(function mySucces(response) {
      $scope.infectedPoints = response.data;

    }, function myError(response) {
      $scope.infectedPoints = response.statusText;
  });


  //Search survivor function by ID. The ID is inside the link itself,
  //together with the input data
  $scope.searchSurvivor = function(){
    $http({
      method: "GET",
      url : "http://zssn-backend-example.herokuapp.com/api/people/" + $scope.ID + ".json"
    }).then(function success(response) {

      $scope.survivorFound = response.data.name;
      //Allows div to show the search result for survivor's name
      $scope.showProfile = true;

    }, function error(response){
      $scope.survivorFound = response.statusText;
      //In case there is no survivor with that input,
      //shows the user the survivor was not found
      $scope.showError = true;
    });
  }
  // Update survivor location function. Use the "name", "age" and "gender" informations,
  // generated by the search of survivor (by ID). The user will not 
  //to insert the data manually.
  $scope.updateLocation = function(){

    // Variable to save the date
    var survivor;

     $http({
      method: "GET",
      url : "http://zssn-backend-example.herokuapp.com/api/people/" + $scope.ID + ".json"
    }).then(function success(response) {
      // Save search data about a survivor
      survivor = response.data;

    }, function error(response){
      //Save error in case it happens
      survivor = response.statusText;
    });

    //Organize the variable "lonlat" to be sent in parameters
    var lonlat = "POINT (" + $scope.latUpdate + " " + $scope.longUpdate + ")";

    //Calls the PATCH request to update the location of survivor
    //Sends the ID as parameter in the link
    $http({
      method: "PATCH",
      url: "http://zssn-backend-example.herokuapp.com/api/people/" + $scope.ID + ".json",
      data: {
      name: survivor.name,
      age: survivor.age,
      gender: survivor.gender,
      lonlat: lonlat
    }

    }).then(function success(response){
      //Feedback in case the location update was successful
      $scope.locationUpdated = response.data.location;
    }, function error(response){
      //Feedback in case something has gone wrong during the update
      $scope.locationUpdated = response.statusText;
    });
  }


});
